import { addDays, subDays } from "date-fns";
import type { Area, Tag, Task } from "../domain/task";
import { defaultOwnerTimeZone, ownerToday } from "../domain/task-date";

const now = new Date();

export function mockToday(
  ownerTimeZone = defaultOwnerTimeZone,
  currentTime = Date.now(),
) {
  return ownerToday(ownerTimeZone, currentTime);
}

const initialToday = mockToday(defaultOwnerTimeZone, now.getTime());
export const yesterday = ownerToday(
  defaultOwnerTimeZone,
  subDays(now, 1).getTime(),
);
export const tomorrow = ownerToday(
  defaultOwnerTimeZone,
  addDays(now, 1).getTime(),
);
export const inThreeDays = ownerToday(
  defaultOwnerTimeZone,
  addDays(now, 3).getTime(),
);

// These IDs and Areas belong only to the Web test scenario, not to product defaults.
export const testAreaIds = {
  aiIt: 101,
  develop: 102,
  music: 103,
  home: 104,
  job: 105,
  pkm: 106,
  routine: 107,
  inbox: 108,
} as const;

export function createTestAreas(): Area[] {
  return [
    {
      id: testAreaIds.aiIt,
      name: "AI/IT",
      color: "blue",
      position: 1,
      isSystemManaged: false,
    },
    {
      id: testAreaIds.develop,
      name: "Develop",
      color: "purple",
      position: 2,
      isSystemManaged: false,
    },
    {
      id: testAreaIds.music,
      name: "Music",
      color: "green",
      position: 3,
      isSystemManaged: false,
    },
    {
      id: testAreaIds.home,
      name: "Home",
      color: "yellow",
      position: 4,
      isSystemManaged: false,
    },
    {
      id: testAreaIds.job,
      name: "Job",
      color: "orange",
      position: 5,
      isSystemManaged: false,
    },
    {
      id: testAreaIds.pkm,
      name: "PKM",
      color: "pink",
      position: 6,
      isSystemManaged: false,
    },
    {
      id: testAreaIds.routine,
      name: "Routine",
      color: "brown",
      position: 7,
      isSystemManaged: false,
    },
    {
      id: testAreaIds.inbox,
      name: "Inbox",
      color: "gray",
      position: 0,
      isSystemManaged: true,
    },
  ];
}

export const initialTags: Tag[] = [
  { id: 1, name: "admin" },
  { id: 2, name: "backend" },
  { id: 3, name: "buy" },
  { id: 4, name: "cloudflare" },
  { id: 5, name: "frontend" },
  { id: 6, name: "health" },
  { id: 7, name: "prototype" },
  { id: 8, name: "review" },
  { id: 9, name: "studio" },
];

export function mockTags(...names: string[]) {
  return names.map((name) => {
    const tag = initialTags.find((candidate) => candidate.name === name);
    if (!tag) throw new Error(`Unknown mock Tag: ${name}`);
    return tag;
  });
}

const initialTaskSeed: Omit<Task, "updatedAt">[] = [
  {
    id: "task-task-management-mvp",
    title: "Taskseq MVP",
    path: ["Develop", "Taskseq MVP"],
    areaId: testAreaIds.develop,
    status: "OPEN",
    start: null,
    due: null,
    completedAt: null,
    tags: [],
    description: "個人用TaskseqをCloudflare上で運用可能にする。",
    workNotes: "",
  },
  {
    id: "task-ui-prototype",
    title: "UI prototype",
    path: ["Develop", "Taskseq MVP", "UI prototype"],
    areaId: testAreaIds.develop,
    parentId: "task-task-management-mvp",
    status: "OPEN",
    start: null,
    due: null,
    completedAt: null,
    tags: mockTags("prototype"),
    description: "主要画面の構成と操作を確認する。",
    workNotes: "",
  },
  {
    id: "task-summer-ep",
    title: "Summer EP",
    path: ["Music", "Summer EP"],
    areaId: testAreaIds.music,
    status: "OPEN",
    start: null,
    due: null,
    completedAt: null,
    tags: [],
    description: "4曲入りEPを完成させる。",
    workNotes: "",
  },
  {
    id: "task-mobile-verification",
    title: "Mobile verification",
    path: ["Develop", "Taskseq MVP", "UI prototype", "Mobile verification"],
    areaId: testAreaIds.develop,
    parentId: "task-ui-prototype",
    status: "OPEN",
    start: null,
    due: null,
    completedAt: null,
    tags: mockTags("prototype"),
    description: "Mobile browserで主要画面を確認する。",
    workNotes: "",
  },
  {
    id: "task-iphone-safari",
    title: "iPhone Safari",
    path: [
      "Develop",
      "Taskseq MVP",
      "UI prototype",
      "Mobile verification",
      "iPhone Safari",
    ],
    areaId: testAreaIds.develop,
    parentId: "task-mobile-verification",
    status: "OPEN",
    start: null,
    due: null,
    completedAt: null,
    tags: mockTags("prototype"),
    description: "iPhone Safariでresponsive layoutを確認する。",
    workNotes: "",
  },
  {
    id: "task-touch-interactions",
    title: "Touch interactions",
    path: [
      "Develop",
      "Taskseq MVP",
      "UI prototype",
      "Mobile verification",
      "iPhone Safari",
      "Touch interactions",
    ],
    areaId: testAreaIds.develop,
    parentId: "task-iphone-safari",
    status: "OPEN",
    start: null,
    due: null,
    completedAt: null,
    tags: mockTags("prototype"),
    description: "Touch操作とdrag操作を確認する。",
    workNotes: "",
  },
  {
    id: "task-track-2",
    title: "Track 2",
    path: ["Music", "Summer EP", "Track 2"],
    areaId: testAreaIds.music,
    parentId: "task-summer-ep",
    status: "OPEN",
    start: null,
    due: null,
    completedAt: null,
    tags: mockTags("studio"),
    description: "Track 2を完成させる。",
    workNotes: "",
  },
  {
    id: "task-desk-refresh",
    title: "Desk refresh",
    path: ["Home", "Desk refresh"],
    areaId: testAreaIds.home,
    status: "OPEN",
    start: null,
    due: null,
    completedAt: null,
    tags: [],
    description: "集中しやすい机へ整える。",
    workNotes: "",
  },
  {
    id: "task-vault-review",
    title: "Vault review",
    path: ["PKM", "Vault review"],
    areaId: testAreaIds.pkm,
    status: "OPEN",
    start: null,
    due: null,
    completedAt: null,
    tags: mockTags("review"),
    description: "Knowledge baseの再利用経路を見直す。",
    workNotes: "",
  },
  {
    id: "task-1",
    title: "Navigation shellを比較する",
    path: [
      "Develop",
      "Taskseq MVP",
      "UI prototype",
      "Navigation shellを比較する",
    ],
    areaId: testAreaIds.develop,
    parentId: "task-ui-prototype",
    status: "OPEN",
    start: yesterday,
    due: yesterday,
    completedAt: null,
    tags: mockTags("prototype", "frontend"),
    description: "Mac幅とiPhone幅で3案を比較する。",
    workNotes: "",
  },
  {
    id: "task-2",
    title: "API contractを確認する",
    path: ["Develop", "Taskseq MVP", "API contractを確認する"],
    areaId: testAreaIds.develop,
    parentId: "task-task-management-mvp",
    status: "OPEN",
    start: initialToday,
    due: initialToday,
    completedAt: null,
    tags: mockTags("backend"),
    description: "`/api/v1/*` のresponse shapeを確認する。",
    workNotes: "",
  },
  {
    id: "task-3",
    title: "ギターのリズムトラックを録る",
    path: ["Music", "Summer EP", "Track 2", "ギターのリズムトラックを録る"],
    areaId: testAreaIds.music,
    parentId: "task-track-2",
    status: "OPEN",
    start: initialToday,
    due: tomorrow,
    completedAt: null,
    tags: mockTags("studio"),
    description: "テンポ112。クリーンとdriveを各2 take。",
    workNotes: "",
  },
  {
    id: "task-4",
    title: "請求書を送る",
    path: ["Job", "請求書を送る"],
    areaId: testAreaIds.job,
    status: "OPEN",
    start: initialToday,
    due: initialToday,
    completedAt: null,
    tags: mockTags("admin"),
    description: "6月分の作業時間を確認して送付する。",
    workNotes: "",
  },
  {
    id: "task-5",
    title: "Daily noteをreviewする",
    path: ["PKM", "Daily noteをreviewする"],
    areaId: testAreaIds.pkm,
    status: "COMPLETED",
    start: initialToday,
    due: initialToday,
    completedAt: now.toISOString(),
    tags: mockTags("review"),
    description: "",
    workNotes: "未処理リンクを2件Wikiへ移動。",
  },
  {
    id: "task-6",
    title: "ストレッチをする",
    path: ["Routine", "Morning", "ストレッチをする"],
    areaId: testAreaIds.routine,
    parentId: "task-morning",
    status: "OPEN",
    start: initialToday,
    due: initialToday,
    completedAt: null,
    tags: mockTags("health"),
    description: "肩と股関節を10分。",
    workNotes: "",
  },
  {
    id: "task-7",
    title: "Cloudflare Accessの設定例を読む",
    path: ["AI/IT", "Cloudflare Accessの設定例を読む"],
    areaId: testAreaIds.aiIt,
    status: "OPEN",
    start: tomorrow,
    due: inThreeDays,
    completedAt: null,
    tags: mockTags("cloudflare"),
    description: "",
    workNotes: "",
  },
  {
    id: "task-8",
    title: "デスクライト候補を整理する",
    path: ["Home", "Desk refresh", "デスクライト候補を整理する"],
    areaId: testAreaIds.home,
    parentId: "task-desk-refresh",
    status: "OPEN",
    start: inThreeDays,
    due: inThreeDays,
    completedAt: null,
    tags: mockTags("buy"),
    description: "",
    workNotes: "",
  },
  {
    id: "inbox-1",
    title: "歯科検診を予約する",
    path: ["Inbox", "歯科検診を予約する"],
    areaId: testAreaIds.inbox,
    status: "OPEN",
    start: null,
    due: null,
    completedAt: null,
    tags: [],
    description: "平日夕方の空きを確認。",
    workNotes: "",
  },
  {
    id: "inbox-2",
    title: "読書メモからTaskを切り出す",
    path: ["Inbox", "読書メモからTaskを切り出す"],
    areaId: testAreaIds.inbox,
    status: "OPEN",
    start: null,
    due: yesterday,
    completedAt: null,
    tags: mockTags("review"),
    description: "",
    workNotes: "",
  },
  {
    id: "trash-1",
    title: "古い機材リストを整理する",
    path: ["Music", "古い機材リストを整理する"],
    areaId: testAreaIds.music,
    status: "OPEN",
    start: null,
    due: null,
    completedAt: null,
    tags: [],
    description: "",
    workNotes: "",
    trashedAt: subDays(now, 4).toISOString(),
  },
];

export const initialTasks: Task[] = initialTaskSeed.map((task) => ({
  ...task,
  updatedAt: "2026-08-05T00:00:00.000Z",
}));
